version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - mvn clean install
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Maven project...
      - mvn package
      - mv target/*.jar app.jar
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - mv app.jar target/
      - mvn clean

