version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - sudo mvn clean install
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Maven project...
      - sudo mvn package
      - sudo mv target/*.jar app.jar
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - sudo mv app.jar target/
      - sudo mvn clean

