version: 0.2

phases:
  install:
    commands:
      - echo Installing system dependencies...
  pre_build:
    commands:
      - echo Preparing for build...
      - mvn clean 
      - mvn clean install
  build:
    commands:
      - echo Building the Maven project...
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying...

