version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing system dependencies...
      - sudo apt-get update
      - sudo apt-get install -y maven
  pre_build:
    commands:
      - echo Preparing for build...
      - mvn clean install -DskipTests=true -e -X || { echo "Maven build failed"; exit 1; }
  build:
    commands:
      - echo Building the Maven project...
      - mvn package -DskipTests=true
      - mv target/*.jar app.jar
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying...
